class Member {
  String name;
  String filiacao_pai;
  String filiacao_mae;
  String data_nascimento;
  String nacionalidade;
  String naturalidade;
  String estado;
  String estado_civil;
  String? profissao;
  String? escolaridade;
  String? titulo_eleitor;
  String tipo_certidao;
  String numero_certidao;
  String data_batismo;
  String igreja;
  String data_admissao;
  String rg;
  String cpf;
  String conjuge;
  String matricula;
  String cargo;
  String membro_igreja;
  String data_saida;
  String procedencia;
  String endereco;
  Member({
    required this.name,
    required this.filiacao_pai,
    required this.filiacao_mae,
    required this.data_nascimento,
    required this.nacionalidade,
    required this.naturalidade,
    required this.estado,
    required this.estado_civil,
    required this.profissao,
    required this.escolaridade,
    required this.titulo_eleitor,
    required this.tipo_certidao,
    required this.numero_certidao,
    required this.data_batismo,
    required this.igreja,
    required this.data_admissao,
    required this.rg,
    required this.cpf,
    required this.conjuge,
    required this.matricula,
    required this.cargo,
    required this.membro_igreja,
    required this.data_saida,
    required this.procedencia,
    required this.endereco,
  });
}
